name: Commitlint

on:
  pull_request:
    branches: [main]

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Check commit messages
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: commitlint.config.cjs
